/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderTheHoodRouteImport } from './routes/under-the-hood'
import { Route as TwonumbersRouteImport } from './routes/twonumbers'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as RecordRouteImport } from './routes/record'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as MethodRouteImport } from './routes/method'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForItRouteImport } from './routes/for-it'
import { Route as ForCounselRouteImport } from './routes/for-counsel'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as CioRouteImport } from './routes/cio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegacyExtractorRouteImport } from './routes/legacy/extractor'
import { Route as InternalHarnessRouteImport } from './routes/internal/harness'
import { Route as LegacyRadiologyStipendRouteImport } from './routes/legacy/radiology/stipend'

const UnderTheHoodRoute = UnderTheHoodRouteImport.update({
  id: '/under-the-hood',
  path: '/under-the-hood',
  getParentRoute: () => rootRouteImport,
} as any)
const TwonumbersRoute = TwonumbersRouteImport.update({
  id: '/twonumbers',
  path: '/twonumbers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForItRoute = ForItRouteImport.update({
  id: '/for-it',
  path: '/for-it',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCounselRoute = ForCounselRouteImport.update({
  id: '/for-counsel',
  path: '/for-counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const CioRoute = CioRouteImport.update({
  id: '/cio',
  path: '/cio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyExtractorRoute = LegacyExtractorRouteImport.update({
  id: '/legacy/extractor',
  path: '/legacy/extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalHarnessRoute = InternalHarnessRouteImport.update({
  id: '/internal/harness',
  path: '/internal/harness',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRadiologyStipendRoute = LegacyRadiologyStipendRouteImport.update({
  id: '/legacy/radiology/stipend',
  path: '/legacy/radiology/stipend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cio': typeof CioRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/for-counsel': typeof ForCounselRoute
  '/for-it': typeof ForItRoute
  '/legal': typeof LegalRoute
  '/method': typeof MethodRoute
  '/optimizer': typeof OptimizerRoute
  '/record': typeof RecordRoute
  '/sandbox': typeof SandboxRoute
  '/site': typeof SiteRoute
  '/story': typeof StoryRoute
  '/twonumbers': typeof TwonumbersRoute
  '/under-the-hood': typeof UnderTheHoodRoute
  '/internal/harness': typeof InternalHarnessRoute
  '/legacy/extractor': typeof LegacyExtractorRoute
  '/legacy/radiology/stipend': typeof LegacyRadiologyStipendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cio': typeof CioRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/for-counsel': typeof ForCounselRoute
  '/for-it': typeof ForItRoute
  '/legal': typeof LegalRoute
  '/method': typeof MethodRoute
  '/optimizer': typeof OptimizerRoute
  '/record': typeof RecordRoute
  '/sandbox': typeof SandboxRoute
  '/site': typeof SiteRoute
  '/story': typeof StoryRoute
  '/twonumbers': typeof TwonumbersRoute
  '/under-the-hood': typeof UnderTheHoodRoute
  '/internal/harness': typeof InternalHarnessRoute
  '/legacy/extractor': typeof LegacyExtractorRoute
  '/legacy/radiology/stipend': typeof LegacyRadiologyStipendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cio': typeof CioRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/for-counsel': typeof ForCounselRoute
  '/for-it': typeof ForItRoute
  '/legal': typeof LegalRoute
  '/method': typeof MethodRoute
  '/optimizer': typeof OptimizerRoute
  '/record': typeof RecordRoute
  '/sandbox': typeof SandboxRoute
  '/site': typeof SiteRoute
  '/story': typeof StoryRoute
  '/twonumbers': typeof TwonumbersRoute
  '/under-the-hood': typeof UnderTheHoodRoute
  '/internal/harness': typeof InternalHarnessRoute
  '/legacy/extractor': typeof LegacyExtractorRoute
  '/legacy/radiology/stipend': typeof LegacyRadiologyStipendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cio'
    | '/economics'
    | '/faq'
    | '/for-counsel'
    | '/for-it'
    | '/legal'
    | '/method'
    | '/optimizer'
    | '/record'
    | '/sandbox'
    | '/site'
    | '/story'
    | '/twonumbers'
    | '/under-the-hood'
    | '/internal/harness'
    | '/legacy/extractor'
    | '/legacy/radiology/stipend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cio'
    | '/economics'
    | '/faq'
    | '/for-counsel'
    | '/for-it'
    | '/legal'
    | '/method'
    | '/optimizer'
    | '/record'
    | '/sandbox'
    | '/site'
    | '/story'
    | '/twonumbers'
    | '/under-the-hood'
    | '/internal/harness'
    | '/legacy/extractor'
    | '/legacy/radiology/stipend'
  id:
    | '__root__'
    | '/'
    | '/cio'
    | '/economics'
    | '/faq'
    | '/for-counsel'
    | '/for-it'
    | '/legal'
    | '/method'
    | '/optimizer'
    | '/record'
    | '/sandbox'
    | '/site'
    | '/story'
    | '/twonumbers'
    | '/under-the-hood'
    | '/internal/harness'
    | '/legacy/extractor'
    | '/legacy/radiology/stipend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CioRoute: typeof CioRoute
  EconomicsRoute: typeof EconomicsRoute
  FaqRoute: typeof FaqRoute
  ForCounselRoute: typeof ForCounselRoute
  ForItRoute: typeof ForItRoute
  LegalRoute: typeof LegalRoute
  MethodRoute: typeof MethodRoute
  OptimizerRoute: typeof OptimizerRoute
  RecordRoute: typeof RecordRoute
  SandboxRoute: typeof SandboxRoute
  SiteRoute: typeof SiteRoute
  StoryRoute: typeof StoryRoute
  TwonumbersRoute: typeof TwonumbersRoute
  UnderTheHoodRoute: typeof UnderTheHoodRoute
  InternalHarnessRoute: typeof InternalHarnessRoute
  LegacyExtractorRoute: typeof LegacyExtractorRoute
  LegacyRadiologyStipendRoute: typeof LegacyRadiologyStipendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/under-the-hood': {
      id: '/under-the-hood'
      path: '/under-the-hood'
      fullPath: '/under-the-hood'
      preLoaderRoute: typeof UnderTheHoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twonumbers': {
      id: '/twonumbers'
      path: '/twonumbers'
      fullPath: '/twonumbers'
      preLoaderRoute: typeof TwonumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-it': {
      id: '/for-it'
      path: '/for-it'
      fullPath: '/for-it'
      preLoaderRoute: typeof ForItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-counsel': {
      id: '/for-counsel'
      path: '/for-counsel'
      fullPath: '/for-counsel'
      preLoaderRoute: typeof ForCounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cio': {
      id: '/cio'
      path: '/cio'
      fullPath: '/cio'
      preLoaderRoute: typeof CioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/extractor': {
      id: '/legacy/extractor'
      path: '/legacy/extractor'
      fullPath: '/legacy/extractor'
      preLoaderRoute: typeof LegacyExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/harness': {
      id: '/internal/harness'
      path: '/internal/harness'
      fullPath: '/internal/harness'
      preLoaderRoute: typeof InternalHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/radiology/stipend': {
      id: '/legacy/radiology/stipend'
      path: '/legacy/radiology/stipend'
      fullPath: '/legacy/radiology/stipend'
      preLoaderRoute: typeof LegacyRadiologyStipendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CioRoute: CioRoute,
  EconomicsRoute: EconomicsRoute,
  FaqRoute: FaqRoute,
  ForCounselRoute: ForCounselRoute,
  ForItRoute: ForItRoute,
  LegalRoute: LegalRoute,
  MethodRoute: MethodRoute,
  OptimizerRoute: OptimizerRoute,
  RecordRoute: RecordRoute,
  SandboxRoute: SandboxRoute,
  SiteRoute: SiteRoute,
  StoryRoute: StoryRoute,
  TwonumbersRoute: TwonumbersRoute,
  UnderTheHoodRoute: UnderTheHoodRoute,
  InternalHarnessRoute: InternalHarnessRoute,
  LegacyExtractorRoute: LegacyExtractorRoute,
  LegacyRadiologyStipendRoute: LegacyRadiologyStipendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
