/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderTheHoodRouteImport } from './routes/under-the-hood'
import { Route as TwonumbersRouteImport } from './routes/twonumbers'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'

const UnderTheHoodRoute = UnderTheHoodRouteImport.update({
  id: '/under-the-hood',
  path: '/under-the-hood',
  getParentRoute: () => rootRouteImport,
} as any)
const TwonumbersRoute = TwonumbersRouteImport.update({
  id: '/twonumbers',
  path: '/twonumbers',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/sandbox': typeof SandboxRoute
  '/site': typeof SiteRoute
  '/twonumbers': typeof TwonumbersRoute
  '/under-the-hood': typeof UnderTheHoodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/sandbox': typeof SandboxRoute
  '/site': typeof SiteRoute
  '/twonumbers': typeof TwonumbersRoute
  '/under-the-hood': typeof UnderTheHoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/sandbox': typeof SandboxRoute
  '/site': typeof SiteRoute
  '/twonumbers': typeof TwonumbersRoute
  '/under-the-hood': typeof UnderTheHoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/sandbox'
    | '/site'
    | '/twonumbers'
    | '/under-the-hood'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faq' | '/sandbox' | '/site' | '/twonumbers' | '/under-the-hood'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/sandbox'
    | '/site'
    | '/twonumbers'
    | '/under-the-hood'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  SandboxRoute: typeof SandboxRoute
  SiteRoute: typeof SiteRoute
  TwonumbersRoute: typeof TwonumbersRoute
  UnderTheHoodRoute: typeof UnderTheHoodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/under-the-hood': {
      id: '/under-the-hood'
      path: '/under-the-hood'
      fullPath: '/under-the-hood'
      preLoaderRoute: typeof UnderTheHoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twonumbers': {
      id: '/twonumbers'
      path: '/twonumbers'
      fullPath: '/twonumbers'
      preLoaderRoute: typeof TwonumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  SandboxRoute: SandboxRoute,
  SiteRoute: SiteRoute,
  TwonumbersRoute: TwonumbersRoute,
  UnderTheHoodRoute: UnderTheHoodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
